name: checkride_mobile
description: "checkride for riders"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  authentication_repository:
    path: packages/authentication_repository

  user_repository:
    path: packages/user_repository

  bloc: ^8.1.4
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  google_fonts: ^6.2.1
  http: ^1.2.1
  formz: ^0.7.0
  stream_transform: ^2.0.0

  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.0
  mocktail: ^1.0.0

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/background.jpg
